package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Composite'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("Composite")
    name = "Composite"

    type = BuildTypeSettings.Type.COMPOSITE

    vcs {
        showDependenciesChanges = true
    }

    dependencies {
        dependency(RelativeId("Main")) {
            snapshot {
            }

            artifacts {
                artifactRules = "*.zip"
            }
        }
    }
}))

